name: .NET

on:
  push:
    branches: [ main ]
    path-ignore: ['abstractions/**', '**.md', '.vscode/**', '**.svg']
  pull_request:
    path-ignore: ['abstractions/**', '**.md', '.vscode/**', '**.svg']

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore kiota.sln
    - name: Build
      run: dotnet build kiota.sln --no-restore
    - name: Test
      run: dotnet test kiota.sln --no-build --verbosity normal --collect:"XPlat Code Coverage"
    - name: Install report generator
      run: dotnet tool install --global dotnet-reportgenerator-globaltool
    - name: Generate coverage report
      run: reportgenerator -reports:**/coverage.cobertura.xml -targetdir:./reports/coverage
    - uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: reports/coverage

  update_coverage:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: coverage
    - name: Get branch name
      run: |
        $branchName = $Env:GITHUB_REF.replace("refs/heads/", "")
        echo "CURRENT_BRANCH=${branchName}" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh
    - run: |
        $content = Get-Content -Path .\reports\coverage\index.html -Raw
        $content -match "<tr><th>Branch coverage:<\/th><td>([\d.]+)%"
        $cov = [float]::Parse($matches[1])
        if($cov > 80) {
          $color = "green"
        } elseif($cov > 50) {
          $color = "orange"
        } else {
          $color = "red"
        }
        $url = "https://img.shields.io/badge/coverage-$cov%25-$color"
        Invoke-WebRequest -Uri $url -OutFile coverage.svg
      shell: pwsh
    - name: push
      uses: github-actions-x/commit@v2.7
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: ${{ env.CURRENT_BRANCH }}
        commit-message: '- updates coverage'
        force-add: 'true'
        files: coverage.svg
        name: Microsoft Graph DevX Tooling
        email: GraphTooling@service.microsoft.com
    